clear;
clc;

nodesFile = "2026-05-01T07-29_export.csv";
edgesFile = "2026-05-01T07-30_export.csv";

nodesOutputFile = "nodes_valais_filtered.csv";
edgesOutputFile = "edges_valais_filtered.csv";

[nodes_roi, edges_roi] = filter_valais_grid( ...
    nodesFile, ...
    edgesFile, ...
    nodesOutputFile, ...
    edgesOutputFile ...
);